artifact_location: /home/will/workspace/Plants-Diseases/api/<https:/my-tracking-server:5000>/0
creation_time: 1717896187040
experiment_id: '0'
last_update_time: 1717896187040
lifecycle_stage: active
name: Default
