site_name: Plants Diseases

copyright: "Copyright &copy; 2023"

theme:
  name: material
  language: "pt"
  palette:
    primary: light green
    accent: amber
# features:
#     - navigation.tabs
  font:
    text: "Reddit Mono"
    code: "sans-serif"
  logo: assets/leafFavcon.svg
  favicon: assets/leafFavcon.svg
